### ISSUE TITLE
Reordering example: Use Spec instead of Brick?

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Tutorials#5]
First: I'm not against using Brick at all and second: don't want to stop inspiration if @StephanEggermont wants to go deeper with Brick widgets. Just to add some feedback.
My comment:

As the central point of the example seems to be the nice drag-and-drop to order and group/ungroup the Bloc elements... maybe the example could be even smaller to load just using Spec for the buttons and then prune Brick as dependency.

**Comment by StephanEggermont** [comment]
The example can indeed be build using pure Bloc. It was just minimally ported from the current GToolkit, where the available buttons are Brick-based

**Comment by tinchodias** [comment]
Thanks, I did the migration in #9
